defaults:
  -
    scope:
        path: ""
    values:
        layout: "default"
        author: "Ryan McQueen"
  -
    scope:
        path: ""
        type: "posts"
        paginate: 10
    values:
        layout: "post"
        permalink: :categories/:year/:month/:day/:title/
